### ISSUE TITLE
Train is too fast

### ISSUE THREAD

**Issue by guillermofbriceno** [SmashedRockSoftware/Project_MissCrow#1]
Slow down train.

**Comment by IllogicalDesigns** [comment]
Need to know what a good speed is.  There are 4 objects in the scene called Moving.  Each one has a script called ground on it.  The speed on this sets the speed of each one.  Set all of the same or it wont work.

Right now the speed is 100

**Comment by bugmage** [comment]
Try 33?

**Comment by IllogicalDesigns** [comment]
I didn't read the comment before making the changes, but I put 30.  Let's see how that feels
