### ISSUE TITLE
Sound integration

### ISSUE THREAD

**Issue by guillermofbriceno** [SmashedRockSoftware/Project_MissCrow#10]
Add an intuitive way to assign sound clips either a pickup, inspect, or use sound.

**Comment by IllogicalDesigns** [comment]
Got a draft that loads from the resource folder.  So we can create a folder for an item with generic sounds.  Each of these will be load when the appropriate action is used.  There is also a fallback generic option.  It requires exact naming in the folder structure.  Gonna make it a bit more bullet proof and roll it out to all actions.
