### ISSUE TITLE
Floating issue

### ISSUE THREAD

**Issue by guillermofbriceno** [SmashedRockSoftware/Project_MissCrow#11]
Since everything is now a skinned mesh on an armature, the current method to raise and lower objects is broken.

**Comment by IllogicalDesigns** [comment]
[https://litter.catbox.moe/em9wej.gif](url)

Would this be acceptable, seems the Jump animation works, but the float animation is fucked

**Comment by IllogicalDesigns** [comment]
https://litter.catbox.moe/em9wej.gif

**Comment by guillermofbriceno** [comment]
@bugmage to review

**Comment by bugmage** [comment]
looks good to me fam!
