### ISSUE TITLE
Integrate dialogue system

### ISSUE THREAD

**Issue by guillermofbriceno** [SmashedRockSoftware/Project_MissCrow#18]

**Comment by IllogicalDesigns** [comment]
Dialogue is integrated, there are two ways to have dialogue occur.  Through the dialogue script for taking actions and inspect dialogue for inspecting

![Image](https://github.com/user-attachments/assets/b67420e8-cb3c-4193-ae71-c6b7020148e5)



![Image](https://github.com/user-attachments/assets/173a5f88-d52c-4809-b764-6c29437528f7)
