### ISSUE TITLE
Integrate written dialogue

### ISSUE THREAD

**Issue by guillermofbriceno** [SmashedRockSoftware/Project_MissCrow#19]
Blocked by #15

**Comment by IllogicalDesigns** [comment]
car1

- [x] entry1 (work even with opening cutscene [yes])
- [x] Firstexamine1
- [x] Puzzlesolve1
- [x] remove WireWorm

car2

- [x] entry2
- [x] Firstexamine2 (Not written)
- [x] Puzzleresolve2 (Not written)

car3

- [x] Entry3
- [x] Firstexamine3
- [x] Puzzleresolve3

car4
- [ ] <===! Define when after is !===>
- [x] After4
- [x] Entry4
- [x] Firstexamine4
- [x] Puzzleresolve4

car5

- [x] After5
- [x] Chef1
- [x] Chef2
- [x] Chef3
- [x] Chef4
- [x] Entry5
- [x] Prepuzzlestart5

car6

- [x] Entry6
- [x] Scyllith1
- [x] Scyllith2
- [x] Scyllith3
- [ ] Scyllith4
- [ ] Scyllith5

**Comment by IllogicalDesigns** [comment]
blocked by
unclear how Scyllith1-6 are displayed
when after is
Firstexamine2 and Puzzleresolve2 are not written
