### ISSUE TITLE
Add item name pop-up on inventory mouseover

### ISSUE THREAD

**Issue by guillermofbriceno** [SmashedRockSoftware/Project_MissCrow#21]

**Comment by IllogicalDesigns** [comment]
Merged into main

**Comment by IllogicalDesigns** [comment]
https://cdn.discordapp.com/attachments/1263928007970521149/1266798352553611264/Unity_wsnxq4ySWt.gif?ex=66a67567&is=66a523e7&hm=410c72b968b272c7375553d30232fdbec58a919ffb0c3884fa669a43c5432b74&
