### ISSUE TITLE
Tutorial and Hints

### ISSUE THREAD

**Issue by guillermofbriceno** [SmashedRockSoftware/Project_MissCrow#22]
A couple things might not immediately be clear:

- Movement
- Combining things in inventory

**Comment by IllogicalDesigns** [comment]
Added hint to use H to show all objects

**Comment by IllogicalDesigns** [comment]
Fixed the bad combos text.  So there is now a text document with the combos formatted as follows.

wireworm+dirtyrag: This rag is too filthy to wrap the worm in, I need to clean it first!

wireworm and dirtyrag are the scriptable objects, these need to be the exact word.  Capitalization is ignored.  Following the colon is the help for the bad combo.  Feel free to sort using blank lines, these will also be ignored.  I have a python script to generate a combo list, but it can't write the help dialogue or understand the sequence.  It just catches dupes and items that are not pickupable

**Comment by IllogicalDesigns** [comment]
Added a new hint that pops up when an item in car 1 is pickuped, then disappears once a combo is performed.  It just mentions that combos can be made by dragging and dropping items.

**Comment by IllogicalDesigns** [comment]
Added a hint for click to interact.
