### ISSUE TITLE
Grandma wandering

### ISSUE THREAD

**Issue by guillermofbriceno** [SmashedRockSoftware/Project_MissCrow#3]
Greatly increase the radius of Mrs. Crow's destination area when something is clicked, such that she no longer ends up in front of things (things the player clicked on) as often.

**Comment by IllogicalDesigns** [comment]
I think in addition to the radius I need to change it so Grandma looks at the thing she is moving towards

**Comment by IllogicalDesigns** [comment]
Granny now has a radius of 2 instead of 0.  I also fixed how things were picked up, as we know when the player has finished their movement.  Might expand this a bit for other actions.
