### ISSUE TITLE
Use updated UI reticle

### ISSUE THREAD

**Issue by guillermofbriceno** [SmashedRockSoftware/Project_MissCrow#34]
Replace UI reticle and UI cursor with supplied ones (Assets > textures > UI textures > "ScrollReticle.png") (Assets > textures > UI textures > Cursors > "Cursor 1")

**Comment by guillermofbriceno** [comment]
@IllogicalDesigns to stop new reticle rotation

**Comment by IllogicalDesigns** [comment]
Also reworked how points are assigned, so when opening the verb wheel all points are placed in the first positions.  This means use is no longer always at position 4, when talk and pickup are missing.  This means it can be at 2 if inspect is present.  Overall this looks better.  Also the reticle no longer rotates!


![Image](https://github.com/user-attachments/assets/66abe4eb-201d-45a1-ae45-48eb7fbd1c1f)
