### ISSUE TITLE
Add moon in sky

### ISSUE THREAD

**Issue by guillermofbriceno** [SmashedRockSoftware/Project_MissCrow#37]

**Comment by IllogicalDesigns** [comment]
Added a moon sphere with an emissive texture



![Image](https://github.com/user-attachments/assets/5a094b8f-23d5-426e-bc65-c963e917012d)

**Comment by guillermofbriceno** [comment]
Thanks, it's up to @bugmage if they want to add a custom texture. Then we can close.
Put texture in Textures folder. Probably will be a sprite. Nothing to replace.

**Comment by IllogicalDesigns** [comment]
![Image](https://github.com/user-attachments/assets/634b10bf-dd5c-473d-9997-dba81c0f928b)
