### ISSUE TITLE
Fix slime animations

### ISSUE THREAD

**Issue by IllogicalDesigns** [SmashedRockSoftware/Project_MissCrow#39]

**Comment by IllogicalDesigns** [comment]
Can you export the slimes again as individual FBX files, I want to see if I can get the animation working properly

**Comment by guillermofbriceno** [comment]
@bugmage to re-export the splines

**Comment by IllogicalDesigns** [comment]
Only 2 of the reimported slimes have animation and they dont animate :(  Not sure what is going wrong

**Comment by IllogicalDesigns** [comment]
Added a punch to the scale, then srink the scale.  Added some particles
