### ISSUE TITLE
Grandma chatter

### ISSUE THREAD

**Issue by guillermofbriceno** [SmashedRockSoftware/Project_MissCrow#4]
She should chatter to herself less frequently, perhaps 1 in clicks.

**Comment by IllogicalDesigns** [comment]
Quips occur at 40% of clicks.  Which is too high.  I want to lower this to too low, then add on some value so eventually it will occur

**Comment by IllogicalDesigns** [comment]
Granny now has been shadow-banned.  Well, she went from a quip chance of 40% to 10%.
