### ISSUE TITLE
Add swing to items in the car

### ISSUE THREAD

**Issue by IllogicalDesigns** [SmashedRockSoftware/Project_MissCrow#40]

**Comment by IllogicalDesigns** [comment]
It would be cool for things to swing in the car.  I can add this behavior if I have a pivot for each item setup in a reasonable place.  For instance, the hammock could swing or the knives.  But I need a pivot placed at the handle of each item and each item separated from it larger object.  Not sure if I should be doing this or Emma as she kinda controls the blender files

**Comment by guillermofbriceno** [comment]
@bugmage to set origin point on pivot point. Re-export everything that needs to be shaking around

**Comment by IllogicalDesigns** [comment]
These have been added, closing
