### ISSUE TITLE
Figure out the pivot issue in Blender and Unity

### ISSUE THREAD

**Issue by IllogicalDesigns** [SmashedRockSoftware/Project_MissCrow#52]

**Comment by IllogicalDesigns** [comment]
When exporting from blender to unity.  Some items have pivots that are set way off from where the item exists.  This is an issue as in Unity the pivot is used to place the object.

Here is an example of a bad pivot.  The item is offset by hundreds of units.  Rotating or moving the item then must account for this.  Which has just led to bugs and bugs and bugs
![Image](https://github.com/user-attachments/assets/1f918458-fb6b-4464-8dcc-6d013f8ea667)


Here is a good pivot from the swingable skull.  It might be hard to tell, but this is where the string is.   This allows for animations to play properly and for scripts to easily be created to swing the skull or other things.
![Image](https://github.com/user-attachments/assets/060cb814-6fc0-4884-9b80-595027da097c)

**Comment by bugmage** [comment]
![image](https://github.com/user-attachments/assets/8b701f9e-bcf8-4246-9469-f3f6a9a27e3b)

from my perspective, these objects already have good pivot points. Is there something I should do? (Armatures and mesh origin points also match one another)
(screenshot from within blender)

**Comment by bugmage** [comment]
![image](https://github.com/user-attachments/assets/b2a6afcd-6840-4560-b40a-a421636db78b)

![image](https://github.com/user-attachments/assets/c62fbee1-2ae4-4664-bac3-af97458bb1df)

I tried to put everything at 0 0 0 in blender before exporting to unity. I hope this is the solution, keep me updated. If this is indeed the solution, I will re export everything that would require it
